theme: minima
title: My Coding Journey
author: Yoshi
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The purpose is to share what I learned in my codinng journey.  I try to write code on a daily basis.

# social links
twitter_username: yoshi_code03 # DO NOT include the @ character, or else the build will fail!
github_username:  ysstudio22 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
